# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, deployment_id: str=None, status_url: str=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param deployment_id: The deployment_id of this InlineResponse201.  # noqa: E501
        :type deployment_id: str
        :param status_url: The status_url of this InlineResponse201.  # noqa: E501
        :type status_url: str
        """
        self.swagger_types = {
            'deployment_id': str,
            'status_url': str
        }

        self.attribute_map = {
            'deployment_id': 'deploymentId',
            'status_url': 'status_url'
        }

        self._deployment_id = deployment_id
        self._status_url = status_url

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def deployment_id(self) -> str:
        """Gets the deployment_id of this InlineResponse201.


        :return: The deployment_id of this InlineResponse201.
        :rtype: str
        """
        return self._deployment_id

    @deployment_id.setter
    def deployment_id(self, deployment_id: str):
        """Sets the deployment_id of this InlineResponse201.


        :param deployment_id: The deployment_id of this InlineResponse201.
        :type deployment_id: str
        """

        self._deployment_id = deployment_id

    @property
    def status_url(self) -> str:
        """Gets the status_url of this InlineResponse201.


        :return: The status_url of this InlineResponse201.
        :rtype: str
        """
        return self._status_url

    @status_url.setter
    def status_url(self, status_url: str):
        """Sets the status_url of this InlineResponse201.


        :param status_url: The status_url of this InlineResponse201.
        :type status_url: str
        """

        self._status_url = status_url
