# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OperationInputParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, data_type: str=None, id: str=None, description: str=None):  # noqa: E501
        """OperationInputParameters - a model defined in Swagger

        :param name: The name of this OperationInputParameters.  # noqa: E501
        :type name: str
        :param data_type: The data_type of this OperationInputParameters.  # noqa: E501
        :type data_type: str
        :param id: The id of this OperationInputParameters.  # noqa: E501
        :type id: str
        :param description: The description of this OperationInputParameters.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'name': str,
            'data_type': str,
            'id': str,
            'description': str
        }

        self.attribute_map = {
            'name': 'name',
            'data_type': 'data_type',
            'id': 'id',
            'description': 'description'
        }

        self._name = name
        self._data_type = data_type
        self._id = id
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'OperationInputParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Operation_input_parameters of this OperationInputParameters.  # noqa: E501
        :rtype: OperationInputParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this OperationInputParameters.


        :return: The name of this OperationInputParameters.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this OperationInputParameters.


        :param name: The name of this OperationInputParameters.
        :type name: str
        """

        self._name = name

    @property
    def data_type(self) -> str:
        """Gets the data_type of this OperationInputParameters.


        :return: The data_type of this OperationInputParameters.
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type: str):
        """Sets the data_type of this OperationInputParameters.


        :param data_type: The data_type of this OperationInputParameters.
        :type data_type: str
        """

        self._data_type = data_type

    @property
    def id(self) -> str:
        """Gets the id of this OperationInputParameters.


        :return: The id of this OperationInputParameters.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this OperationInputParameters.


        :param id: The id of this OperationInputParameters.
        :type id: str
        """

        self._id = id

    @property
    def description(self) -> str:
        """Gets the description of this OperationInputParameters.


        :return: The description of this OperationInputParameters.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this OperationInputParameters.


        :param description: The description of this OperationInputParameters.
        :type description: str
        """

        self._description = description
